BASELINE: Update Chromium to 140.0.7339.225
Change-Id: I57dcb0a813b143bd3073189aed315e8a6b0ec031

diff --git a/chromium/third_party/perfetto/.github/workflows/analyze.yml b/chromium/third_party/perfetto/.github/workflows/analyze.yml
--- a/chromium/third_party/perfetto/.github/workflows/analyze.yml
+++ b/chromium/third_party/perfetto/.github/workflows/analyze.yml
@@ -14,22 +14,20 @@
 
 name: Perfetto CI
 on:
-  # 1. continuous
-  schedule:
-    # Run every 6 hours
-    - cron: "0 */6 * * *"
-
-  # 2. postsubmit
+  # 1. postsubmit
   push:
     branches:
       - main
 
-  # 3. presubmit
+  # 2. presubmit
   pull_request:
     types: [opened, synchronize]
     branches:
       - main
-      - dev/*
+      - dev/**/*
+
+permissions:
+  pull-requests: read
 
 # If a new commit is pushed, cancel previous jobs for the same PR / branch.
 concurrency:
@@ -38,46 +36,114 @@ concurrency:
 
 jobs:
   analyze:
-    runs-on: self-hosted
+    # Unlike other workflows, this runs on the Github ubuntu-latest pool.
+    # This is deliberate: (1) this workflow doesn't need anything special from
+    # our 'sandbox' docker container, and GitHub's pool is just faster.
+    # (2) when our CI autoscaler ramps down, it can take a long time until we
+    # have some capacity to run this. In turn, delaying analyze.yml further
+    # delays in scaling-up because we didn't queue the child jobs.
+    runs-on: ubuntu-latest
     timeout-minutes: 45
+    outputs:
+      TRIVIAL_CHANGE: ${{ steps.trivial.outputs.TRIVIAL_CHANGE }}
+      UI_ONLY_CHANGE: ${{ steps.ui_only.outputs.UI_ONLY_CHANGE }}
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 2
+          fetch-depth: 1
 
-      - name: Check if the change is UI/docs only (skip linux/android tests)
+      # Fetch the upstream branch as well, so we can diff and see the list of
+      # changed files.
+      - name: Fetch upstream branch
+        if: ${{ github.base_ref != '' }}
+        run: git fetch origin ${{ github.base_ref }} --depth=1
+
+      - name: Check if the change is trivial (docs/infra only)
+        id: trivial
         run: |
-          if !(git diff --name-only HEAD^1 HEAD | egrep -qv '^(ui|test/data/ui-screenshots)/'); then
-          echo "UI_ONLY_CHANGE=1" >> $GITHUB_OUTPUT
+          # In postsubmit (cron) github.base_ref is ""
+          if [ -z "${{ github.base_ref }}" ] || git diff --name-only origin/${{ github.base_ref }} HEAD | egrep -qv '^(docs|infra|tools|test/data|[.]github)/'; then
+          echo "TRIVIAL_CHANGE=0" | tee -a $GITHUB_OUTPUT
           else
-          echo "UI_ONLY_CHANGE=0" >> $GITHUB_OUTPUT
+          echo "TRIVIAL_CHANGE=1" | tee -a $GITHUB_OUTPUT
+          fi
+
+      - name: Check if the change is UI only (skip linux/android tests)
+        id: ui_only
+        run: |
+          # In postsubmit (cron) github.base_ref is ""
+          if [ -z "${{ github.base_ref }}" ] || git diff --name-only origin/${{ github.base_ref }} HEAD | egrep -qv '^(ui|test/data/ui-screenshots)/'; then
+          echo "UI_ONLY_CHANGE=0" | tee -a $GITHUB_OUTPUT
+          else
+          echo "UI_ONLY_CHANGE=1" | tee -a $GITHUB_OUTPUT
           fi
 
   linux:
     needs: analyze
-    if: needs.analyze.outputs.UI_ONLY_CHANGE == '0'
+    if:
+      needs.analyze.outputs.UI_ONLY_CHANGE == '0' &&
+      needs.analyze.outputs.TRIVIAL_CHANGE == '0'
     uses: ./.github/workflows/linux-tests.yml
 
   android:
     needs: analyze
-    if: needs.analyze.outputs.UI_ONLY_CHANGE == '0'
+    if:
+      needs.analyze.outputs.UI_ONLY_CHANGE == '0' &&
+      needs.analyze.outputs.TRIVIAL_CHANGE == '0'
     uses: ./.github/workflows/android-tests.yml
 
   ui:
     needs: analyze
+    if: needs.analyze.outputs.TRIVIAL_CHANGE == '0'
     uses: ./.github/workflows/ui-tests.yml
 
   bazel:
     needs: analyze
-    if: needs.analyze.outputs.UI_ONLY_CHANGE == '0'
+    if:
+      needs.analyze.outputs.UI_ONLY_CHANGE == '0' &&
+      needs.analyze.outputs.TRIVIAL_CHANGE == '0'
     uses: ./.github/workflows/bazel-tests.yml
 
   fuzzer:
     needs: analyze
-    if: needs.analyze.outputs.UI_ONLY_CHANGE == '0'
+    if:
+      needs.analyze.outputs.UI_ONLY_CHANGE == '0' &&
+      needs.analyze.outputs.TRIVIAL_CHANGE == '0'
     uses: ./.github/workflows/fuzzer-tests.yml
 
   repo-checks:
     needs: analyze
-    if: needs.analyze.outputs.UI_ONLY_CHANGE == '0'
     uses: ./.github/workflows/repo-checks.yml
+
+  # This final step joins the results of the nested workflows and succeeds if
+  # all the non-skipped workflows have suceeded. This job is used by the
+  # "require CI to pass" GitHub ruleset.
+  ensure-ci-is-green:
+    needs:
+      - analyze
+      - linux
+      - android
+      - ui
+      - bazel
+      - fuzzer
+      - repo-checks
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Ensure all non-skipped jobs have suceeded
+        run: |
+          set -e
+          check() {
+            job="$1"
+            result="$2"
+            if [ "$result" != "success" ] && [ "$result" != "skipped" ]; then
+              echo "::error::$job failed with result: $result"
+              exit 1
+            fi
+          }
+          check linux ${{ needs.linux.result }}
+          check android ${{ needs.android.result }}
+          check ui ${{ needs.ui.result }}
+          check bazel ${{ needs.bazel.result }}
+          check fuzzer ${{ needs.fuzzer.result }}
+          check repo-checks ${{ needs.repo-checks.result }}
